Added functionality to show weeknumbers
ZestfulNation/vue-hotel-datepicker pull request #317
Opened 2022-08-29 09:29 UTC by kasperlegarth

Feature to show week numbers. Highly requested by Scandinavian countries. Fix #81

2022-09-05 16:08 UTC, matiasperrone commented
Awesome! Thanks... I'll do a code review... and then I'll merge it... be patient please.

2022-09-05 17:43 UTC, kasperlegarth commented
> Awesome! Thanks... I'll do a code review... and then I'll merge it... be patient please.

No hurry. Just in your own time. I just thought I would help where I could. Let me know if i should make any modifications. 👍

2022-12-12 16:09 UTC, matiasperrone requested changes

2022-12-12 16:09 UTC, matiasperrone commented on src/DatePicker/components/Month.vue
> +      <div class="vhd__datepicker__weeknumbers__number"  v-for="(day, index) in weekNumbers" :key="index" v-html="getIsoWeek(day.date)"></div>
Please don't use index as a key, because does not allows Vue to properly identify this div among others to update the DOM

2022-12-29 14:03 UTC, matiasperrone commented
@kasperlegarth I didn't get the changes... where you able to do it?

2022-12-29 14:09 UTC, merged

2022-12-29 15:05 UTC, matiasperrone commented
@kasperlegarth hurra! Now we have the week numbers.
Still working in the build.

2022-12-29 15:06 UTC, matiasperrone commented
Is now merge into main in #319